### PR TITLE
Adjust reading projection from rasters

### LINKED ISSUE #64: Unhandled error with unprojected TIF
If a tif comes through that 
- has a coordinate system defined, say epsg:4326
- doesn't have any georeferencing info

Then tools like `gdalinfo` and `rio info` will kinda lead you to believe that they're okay -- until you notice that the pixel dimensions are identical to the geographic extent. That is, one pixel = one degree, and the image is 3000 pixels wide.

Also, [mapnik-omnivore fails here](https://github.com/mapbox/mapnik-omnivore/blob/0931b7768a71dde5d5488632c6d57696adaefc00/lib/datasource-processor.js#L431) in an unhandled fashion, because `ds.geoTransform` was `null` to begin with.

I think we need some kind of check in here that georeferencing information is valid? Is the lack of a geotransform enough / unique to this situation?

cc @GretaCB @sgillies wonder what you guys think? I can provide a test fixture.

### PR DESCRIPTION
**Pull request by rclark**
Makes some changes to the flow when reading projection info from rasters. Compartmentalizes each set of node-gdal calls and provides clearer error messages in the event of a failure.

Fixes #64 

cc @willwhite @GretaCB

### CODE REVIEW

File: lib/datasource-processor.js [hunk 1]
```diff
@@ -459,15 +453,15 @@ function getBands(ds, bandCount){
...
         unitType = ds.bands.get(i).unitType;
         //Error check file sources
-        try { 
+        try {
             bandStats = band.getStatistics(false, true);
         } catch(err){
-            return invalid("Error getting statistics of band. 1 or more of the VRT file's relative sources may be missing: " + err.message);
-        };
+            throw invalid("Error getting statistics of band. 1 or more of the VRT file's relative sources may be missing: " + err.message);
+        }
```
Comment (springmeyer) [inline lib/datasource-processor.js]: Is the `throw` here intentional? It probably is, just double checking since I've noticed most places `return invalid` is used.

Comment (rclark) [inline lib/datasource-processor.js]: Yeah it actually is intentional, because this function [is called synchronously here](https://github.com/mapbox/mapnik-omnivore/blob/4134468b53257108724e8e994b9647ff4c3117c8/lib/datasource-processor.js#L406) and a conditional in the `catch` passes the message along.

**Comment by rclark** [comment]
I don't have any idea why travis builds failed on linux, but not on OSX. It appears that in these cases something related to coveralls failed:
- `npm test` round of tests passed
- `npm run coverage` round of tests passed
- [build failed](https://travis-ci.org/mapbox/mapnik-omnivore/jobs/47810406#L781-L793) with coveralls trying to do I don't know what... maybe send a Github deployment message?

**Comment by GretaCB** [comment]
@rclark I had this issue a couple times back in the summer. Once was due to bad callback flow in my code. The second, I updated instanbul to the most recent version and that seemed to do the trick.

**Comment by rclark** [comment]
Istanbul was up-to-date for these runs (0.3.5) and I have a very hard time understanding how a code bug code result in passed tests everywhere, and then this 

```
[error] "2015-01-21T19:47:08.366Z"  'error from getOptions'
/home/travis/build/mapbox/mapnik-omnivore/node_modules/coveralls/bin/coveralls.js:18
        throw err;
              ^
Error: Command failed: /bin/sh -c git cat-file -p 9eac4b7d42c454cdfc4350019ffa21bc5440a0e3
fatal: Not a valid object name 9eac4b7d42c454cdfc4350019ffa21bc5440a0e3
    at ChildProcess.exithandler (child_process.js:732:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1000:16)
    at Socket.<anonymous> (child_process.js:1168:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:461:12)
```

Tests even passed on this commit, but not the PR. I wonder if its possible that merging #60 between when I made this PR and when the tests ran could've impacted anything? Going to try giving travis a bump.
